version: '3.8'

name: bdr-projet

services:
  postgresql:
    build:
      context: ./database
      dockerfile: Dockerfile
    container_name: bdr-projet-postgresql
    environment:
      - POSTGRESQL_HOST=postgresql
      - POSTGRESQL_USERNAME=bdr
      - POSTGRESQL_PASSWORD=bdr
      - POSTGRESQL_DATABASE=bdr
      - POSTGRESQL_POSTGRES_PASSWORD=root
    ports:
      - "5432:5432"
    volumes:
      - .:/data:ro

  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "7000:7000"
    depends_on:
      - postgresql